appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: MjS1mD34Him44vMQ3jHNcGnI86wbAxAcxFZkWZGt2EzFI3lwpixua4GCMzL5ZXnVfi5FlNY8XOslQiFDxT4kLaYAD4dPln1d4QC9G8ShvL5hvWflRm53CuRkyeLmq7nevh2IrZzBwXc1VFhzf3FDhoAdMiT2URs9WHvarB+rw2x47UbPNihQeistLdiXJuw6plwbJ+yjqskk1J0g9s/iDYRfcYPPbdrHn+QATFF2WLtpdtqG/M8M0zWAO7IFLVABj4PKsOjSigua1eMAT99sxP+7+bL4BNhaLU1pC/z0e9whqLDQIqKu7x3jBT1K/AgXUQzUr77IJGyklYAhwcg9Tg9lTm3Wwi1ZIynLzLmDHTqTC2ceGlwLLHTlDqzMeu2g+sLV6Ei+RYwp0E5TcBejY1i06enPIEACPU7pNhh38ZWbAfzRG28dkJ2HglTIs7PurG2Pw5CRlw4nLJPEhbHu14GJKUZKQOAzejhNxOwh6+wokEMytaUp1tXuoCdpUPydeosjbL9AcAnvvsmzTVZYAsYdma+vwoN3YyNDATyQ453m1oONHPxIFQg58zoTQPYxisNouCNoiMd37vQ1GqR1RSGCFvMBi/uAUa0ECl5t1vvhK3IFvMzdPDjYKG5I07ATwPYafr+EX44j26q2GLrXPM+NF3pUNAVT598+t1RD/gw=}
conda_forge_output_validation: true
